names:
- lid: en-US
  res: Asastarrie Labs
author: X230 NZ-666
email: Unicorn_X230@outlook.com
descriptions:
- lid: en-US
  res: The personal website of X230 NZ666.
- lid: zh-CN
  res: 这里是 X230 大青椒的个人网站。

twitter_username: smartcyborg_230
github_username:  yzhang37
lang_id: zh-CN
beian_info: "沪ICP备16034951号-1"

sass:
    style: compressed

collections:
  uploaders:
    output: true
    permalink: "/av/:year/:month/:day/:title"
  avtags:
    output: false
  failures:
    output: false

lres:
  langname:
  - lid: en-US
    res: "English (United States)"
  - lid: zh-CN
    res: "简体中文"
  - lid: ja-JP
    res: "日本語"
  longdate:
  - lid: en-US
    res: "%A, %B %e, %Y"
  - lid: zh-CN
    res: "%Y年%m月%e日"
  - lid: ja-JP
    res: "%Y年%m月%e日"
  shortdate:
  - lid: en-US
    res: "%m/%e/%Y"
  - lid: zh-CN
    res: "%Y/%m/%e"
  - lid: ja-JP
    res: "%Y/%m/%d"
  res_home_title:
  - lid: en-US
    res: "Home"
  - lid: ja-JP
    res: "ホーム"
  - lid: zh-CN
    res: "主页"
  res_page_bottom_end:
  - lid: en-US
    res: "All good thing come to an end."
  - lid: zh-CN
    res: "我是有底线的。"
  - lid: ja-JP
    res: "え、ここまでか。"
  res_footer_connect:
  - lid: en-US
    res: "Connect"
  - lid: zh-CN
    res: "链接"
  res_avpage_sourcelang:
  - lid: en-US
    res: "Source/Language:"
  - lid: zh-CN
    res: "源/语言:"
  res_avpage_categories:
  - lid: en-US
    res: "Categories:"
  - lid: zh-CN
    res: "分类:"
  res_avpage_nosource:
  - lid: en-US
    res: "No sources available"
  - lid: zh-CN
    res: "没有视频源可用"
  res_avpage_uploadat:
  - lid: en-US
    res: "uploaded at %1"
  - lid: zh-CN
    res: "上传于 %1"

limits:
  av:
    single_tag_max: 6
    single_tag_showmore_bottom: 3
    multitag_max: 12

plattag_styles:
  - pid: bilibili
    names:
    - lid: en-US
      res: Bilibili
    - lid: zh-CN
      res: 哔哩哔哩
    - lid: ja-JP
      res: "ビリービリー"
    bgcolor: "pink lighten-2"
    img_c: 
    img_m: "/assets/logos/bili_mono.png"
  - pid: youtube
    names:
    - lid: en-US
      res: Youtube
    bgcolor: "red"
    img_c: 
    img_m: "/assets/logos/youtube_mono.png"